"""initial schema

Revision ID: 09d19fb21634
Revises:
Create Date: 2026-09-08 16:59:30.626913
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "09d19fb21634"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bible_characters",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("role", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("voice", sa.String(length=40), nullable=False),
        sa.Column("motivation", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("show_id", "name", name="uq_character_per_show"),
    )
    op.create_index(op.f("ix_bible_characters_show_id"), "bible_characters", ["show_id"], unique=False)
    op.create_table(
        "bible_relationships",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("from_character", sa.String(length=80), nullable=False),
        sa.Column("to_character", sa.String(length=80), nullable=False),
        sa.Column("nature", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bible_relationships_show_id"), "bible_relationships", ["show_id"], unique=False)
    op.create_table(
        "bible_world_rules",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bible_world_rules_show_id"), "bible_world_rules", ["show_id"], unique=False)
    op.create_table(
        "episode_summaries",
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("show_id", "episode_number"),
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("episode_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=True),
        sa.Column("requested_by", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("prompt", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_generation_jobs_episode_id"), "generation_jobs", ["episode_id"], unique=False)
    op.create_index(op.f("ix_generation_jobs_show_id"), "generation_jobs", ["show_id"], unique=False)
    op.create_index(op.f("ix_generation_jobs_status"), "generation_jobs", ["status"], unique=False)
    op.create_table(
        "plot_threads",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("introduced_in", sa.Integer(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plot_threads_show_id"), "plot_threads", ["show_id"], unique=False)
    op.create_table(
        "processed_events",
        sa.Column("consumer", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("handled_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("consumer", "event_id"),
    )
    op.create_table(
        "series_bibles",
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("concept", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("arc", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("episode_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("show_id"),
    )
    op.create_table(
        "job_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_table("series_bibles")
    op.drop_table("processed_events")
    op.drop_index(op.f("ix_plot_threads_show_id"), table_name="plot_threads")
    op.drop_table("plot_threads")
    op.drop_index(op.f("ix_generation_jobs_status"), table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_show_id"), table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_episode_id"), table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_table("episode_summaries")
    op.drop_index(op.f("ix_bible_world_rules_show_id"), table_name="bible_world_rules")
    op.drop_table("bible_world_rules")
    op.drop_index(op.f("ix_bible_relationships_show_id"), table_name="bible_relationships")
    op.drop_table("bible_relationships")
    op.drop_index(op.f("ix_bible_characters_show_id"), table_name="bible_characters")
    op.drop_table("bible_characters")
    # ### end Alembic commands ###
