"""initial schema

Revision ID: 2e36ada527d7
Revises:
Create Date: 2026-09-08 17:07:23.572728
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2e36ada527d7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_events",
        sa.Column("consumer", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("handled_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("consumer", "event_id"),
    )
    op.create_table(
        "reco_co_play",
        sa.Column("show_a", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("show_b", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("show_a", "show_b"),
    )
    op.create_table(
        "reco_show_signals",
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("plays", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("completes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("likes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("bookmarks", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("follows", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("unique_listeners", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("trending_score", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("show_id"),
    )
    op.create_table(
        "reco_shows",
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("language_code", sa.String(length=8), nullable=False),
        sa.Column("genre_ids", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("ai_generated", sa.Boolean(), nullable=False),
        sa.Column("creator_id", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("show_id"),
    )
    op.create_index(op.f("ix_reco_shows_language_code"), "reco_shows", ["language_code"], unique=False)
    op.create_index(op.f("ix_reco_shows_published_at"), "reco_shows", ["published_at"], unique=False)
    op.create_table(
        "reco_user_genre_affinity",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("genre_id", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "genre_id"),
    )
    op.create_table(
        "reco_user_language_affinity",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("language_code", sa.String(length=8), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "language_code"),
    )
    op.create_table(
        "reco_user_prefs",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("genre_slugs", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("language_codes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("explicit_ok", sa.Boolean(), nullable=False),
        sa.Column("premium", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "reco_user_show_affinity",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("show_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "show_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reco_user_show_affinity")
    op.drop_table("reco_user_prefs")
    op.drop_table("reco_user_language_affinity")
    op.drop_table("reco_user_genre_affinity")
    op.drop_index(op.f("ix_reco_shows_published_at"), table_name="reco_shows")
    op.drop_index(op.f("ix_reco_shows_language_code"), table_name="reco_shows")
    op.drop_table("reco_shows")
    op.drop_table("reco_show_signals")
    op.drop_table("reco_co_play")
    op.drop_table("processed_events")
    # ### end Alembic commands ###
